#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost/springboot_wechat?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

#微信公众平台
wxpay:
  appid: wxwyyyyyyyyyyyyyyyyyyyy
  appsecret: eeeeeeee

#微信开放平台（用于扫码接口的调用）
wxopen:
  appid: wx025575eac69a2d5b
  appsecret: f5b6730c592ac15b8b1a5aeb8948a9f3
  redirect_url: http://16webtest.tunnel.qydev.com/api/v1/wechat/user/callback

#mybaits
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mapperConfig.xml


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql










